### ISSUE TITLE
Figma Link

### ISSUE THREAD

**Issue by audreystolze** [gxc-challenge-winter21/the-green-mile#28]
Dear Green Mile team,

The link to figma is not working. It says "Prototype not found". Could some please check it asap to correct it?
We would like to finalize your grading asap...

Best Regards and a wonderful holidays season.

Audrey

**Comment by ThmsMtzkr** [comment]
https://www.figma.com/file/RwAh6luudybkP21LzhrzzH/Fold-a-Bike-by-Green-Mile-(Version-2)?node-id=0%3A1

I also ivited you directly through Figma now, by their share option. Further I made some accesspolicies more open. Please let me know if it works. Thanks and sorry for the inconvenience.

**Comment by ThmsMtzkr** [comment]
https://www.figma.com/proto/RwAh6luudybkP21LzhrzzH/Fold-a-Bike-by-Green-Mile-(Version-2)?node-id=10%3A395&scaling=scale-down&page-id=0%3A1&starting-point-node-id=10%3A395

the link to the direct presentation of the prototype is still the same as in our doc, without here now, without scaling parameter

**Comment by ThmsMtzkr** [comment]
now the Figma design is part of a new team. (only one project as free user). So far I only invited @audreystolze  and @Aisa98 in case we need further editors. The links remain the same:  
workspace: https://www.figma.com/file/RwAh6luudybkP21LzhrzzH/Fold-a-Bike-by-Green-Mile-(Version-2)?node-id=0%3A1
prototype: https://www.figma.com/proto/RwAh6luudybkP21LzhrzzH/Fold-a-Bike-by-Green-Mile-(Version-2)?node-id=10%3A395&scaling=scale-down&page-id=0%3A1&starting-point-node-id=10%3A395

**Comment by ThmsMtzkr** [comment]
I did check it with various friends and familymember. From different networks, without a Figma account those people could experience the prototype. How is it holding up on your end?

**Comment by audreystolze** [comment]
Thanks. The links are now working correctly. 

Best Regards
Audrey
